name: flavorbanner
description: Flavor Banner.
version: 1.0.1
homepage: https://github.com/p02diada/flutter-flavor-banner

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  device_info_plus: ^3.2.1
  package_info_plus: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

